### ISSUE TITLE
Calculo do Digito Nosso Numero Caixa Economica

### ISSUE THREAD

**Issue by DIOGENESGUTIERREZ** [impactro/Boleto-ASP.NET#1]
calculo do digito do nosso numero da caixa economica federal esta incorreto. Por exemplo para o numero 9000003225 o digito deve ser 0 (zero) e não 1 (hum) com calculado atualmente. Segundo o manual da caixa, o resultado do calculo do modulo 11 for maior que 9 o digito deverá ser 0, caso contrario o digito deverá ser o numero calculado. Ver manual  em anexo pagina 12 item 5.4.2
[ESPCODBARR_SICOB.pdf](https://github.com/impactro/Boleto-ASP.NET/files/44866/ESPCODBARR_SICOB.pdf)

**Comment by impactro** [comment]
Ola Diogenes, 
Desculpe a demora em responder, mas eu preferi fazer uma analise bem detalhada e revalidar tudo.
Criei mais um projeto no github, que conterá os projetos de testes dos boletos e a resolução de cada caso provando, ou corrigindo de acordo com cada caso.

Veja o link a seguir:
https://github.com/impactro/Boleto-Test/blob/master/Caixa.cs#L171

você pode baixar o projeto e executar em sua máquina, e você verá como saida exatamente a informação abaixo, ou seja, ao meu ver está realmente tudo certo.

Result StandardOutput:  
Linha Digitável: 10499.00127 00200.001287 70000.000128 1 10990000016000
Agência/Conta: 0012.870.00000012.1
Nosso Número: 9001200200-9
Fator Vencimento: 1099
Exemplo Livre: Nosso Número: 9000003225-0

Também neste link das páginas de demostração mostra as 2 formas diferentes de calcular o módulo 11, no caso do Nosso Numero da Caixa realmente usa-se o modulo especial
http://exemplos.boletoasp.com.br/BoletoNet/FuncTeste_Modulo11.aspx

Veja aqui o trecho do código fonte que trata o convenio de 15 dígitos da caixa:

```
            cNossoNumero = CobUtil.Right(cNossoNumero, 10);
            string cLivre = cNossoNumero + cCodCedente;

            blt.NossoNumeroExibicao = cNossoNumero + "-" + CobUtil.Modulo11Especial(cNossoNumero, 9).ToString();

            cCodCedente += CobUtil.Modulo11Padrao(cCodCedente, 9).ToString();
            blt.AgenciaConta =
                cCodCedente.Substring(0, 4) + "." +
                cCodCedente.Substring(4, 3) + "." +
                cCodCedente.Substring(7, 8) + "." +
                cCodCedente.Substring(15, 1);
            return cLivre;
```
