### ISSUE TITLE
posição 106 da remessa da caixa em branco

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-ASP.NET#2]
Olá, não consigo preencher o campo conforme a solicitação do banco.

Exemplo: http://prntscr.com/cc3m3b

O que estou fazendo: http://prntscr.com/cc3n1w

`boleto.SetRegEnumValue(CNAB240SegmentoPCaixa.AgenciaCobradora, "0");`

Solicitação do 1º cliente: http://prntscr.com/cc3nfo
Solicitação do 2º cliente: http://prntscr.com/cc3nvj

**Comment by impactro** [comment]
Esse campo está separado em duas partes, onde um é o numero da agencia, e outro e é digito verificador da agencia, então deixe também zerado essa segunda variável: AgenciaCobradoraDV

```
    /// <summary>
    /// Agência Encarregada da Cobrança *C014 
    /// </summary>
    [RegFormat(RegType.P9, 5)] // 101-105
    AgenciaCobradora,

    /// <summary>
    /// Verificador da Agência’ *C014 
    /// </summary>
    [RegFormat(RegType.PX, 1)] // 106
    AgenciaCobradoraDV,
```
