### ISSUE TITLE
Segmento R da caixa

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-ASP.NET#4]
Bom dia Fábio, tenho uma dúvida do cliente, segue abaixo:

O sistema não está colocando no arquivo remessa o item "R que trata da geração de cobrança de multa conforme pagina 29  do manual cnab240 da caixa e também em anexo.

Fico no aguardo de providencias ou tenho que fazer alguma configuração no programa para que isto funcione.

Grato
Benedito

Como faço para atribuir esta cobrança de multa no item "R"?

Como estou fazendo:
`boleto.SetRegEnumValue(CNAB240SegmentoPCaixa.Juros, 2); 
 boleto.SetRegEnumValue(CNAB240SegmentoPCaixa.JurosMora, boleto.PercentualMora);
 boleto.SetRegEnumValue(CNAB240SegmentoPCaixa.JurosData, boleto.DataVencimento.AddDays(1));`

O que preciso fazer?

Em anexo o documento.
[pagina 29.pdf](https://github.com/impactro/Boleto-ASP.NET/files/449808/pagina.29.pdf)

**Comment by diogolovizon** [comment]
Olá Fábio, a ultima versão não contempla  o segmento R. Tentei implantar o seu exemplo de testes, mas sem sucesso, pra falar a verdade fiquei meio perdido de como incluir. Podes atualizar a dll ou o projeto, ou pode me auxiliar? Abraço!

**Comment by diogolovizon** [comment]
Olá Fábio, é possível dar uma atenção neste caso?
Obrigado.

**Comment by impactro** [comment]
Acho que esse caso seria bom resolvermos junto, via acesso remoto.
Me ligue para agendarmos um horário, no feriado
