### ISSUE TITLE
Remessa Santander apresenta um problema que não existia antes

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-ASP.NET#5]
A nova versão que foi compartilhada contém inconsistências que antes não possuía.

Recebi várias ligações de clientes com problema ao importar a remessa pelo fato de que a quantidade de registros no arquivo não condiz com a posição 2 à 7 no TRAILLER do aquivo .

O Erro diz: CAMPO DEVE INFORMAR TOTAL DE LINHAS NO ARQUIVO, CONTANDO LINHAS HEADER E TRAILLER.

Exemplo: http://prntscr.com/cdbc1y

Atualmente não está contando o header e trailler. Por favor é urgente!

**Comment by impactro** [comment]
Estou no meio de outras mudanças, e ei precisaria tentar descobrri o porque mudei isso.
Mas pelo que verifiquei na documentação é isso mesmo, você está certo.

Na versão mais recente que você baixou apenas altera a linhaabaixo do arquivo "CNAB400Santander.cs"

regArqTrailer[CNAB400SantanderTrailer.Quantidade] = Boletos.NossoNumeros.Count + 2; // adicionando o proprio header e trailer

Na próximo essa versão já conterá isso.
