### ISSUE TITLE
Remessa Sicoob

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-ASP.NET#6]
Olá, segue situação reportada.

ESTAMOS ENVIADO O ARQUIVO PARA O BANCO CREDIJA SICOB, NA INSTRUÇÃO ESTÁ APARECENDO MULTA E MORA, MAS NO ARQUIVO CONFIRMEI AGORA NO O BANCO ESTA INDO ZERADO.

POSIÇÃO R 66 - 88 MULTA
POSIÇÃO T 118 - 141 JUROS

BANCO SICOB CREDIJA 48-3535-6600 CRISTINI 

O que precisa ser feito pra incluir os segmentos R e T?

OBS: Inclusive estou com um problema parecido na Caixa.

[E3100013.TXT](https://github.com/impactro/Boleto-ASP.NET/files/462456/E3100013.TXT)
[E2700011.TXT](https://github.com/impactro/Boleto-ASP.NET/files/462455/E2700011.TXT)
[E2700010.TXT](https://github.com/impactro/Boleto-ASP.NET/files/462458/E2700010.TXT)
[E2300012.TXT](https://github.com/impactro/Boleto-ASP.NET/files/462457/E2300012.TXT)

**Comment by impactro** [comment]
Ola Diogo, quanto ao segmento T, ele é usado apenas para retorno, e nas posições que você indicou tem outro tipo de informação:

![image](https://cloud.githubusercontent.com/assets/1304804/18422330/c3a50efe-786f-11e6-9b97-fad03b8be5fc.png)

Já no segmento P nas posições 118-141 eu aplico a juros de mora conforme a logica abaixo:

![image](https://cloud.githubusercontent.com/assets/1304804/18422473/dc2cf94e-7871-11e6-9f0f-81cbc5d42694.png)

![image](https://cloud.githubusercontent.com/assets/1304804/18422348/0db1205a-7870-11e6-91e1-78da63cc3e23.png)

No caso isso trata-se

![image](https://cloud.githubusercontent.com/assets/1304804/18422511/918f1b5a-7872-11e6-86a6-0969280f0ba9.png)

Mas o valor da multa, é especificado neste segmento "R" opcional.

![image](https://cloud.githubusercontent.com/assets/1304804/18422526/d1cd813e-7872-11e6-9f69-c2192b01dccd.png)

Realmente eu não tenho isso implementado, eu no geral só implemento os registros obrigatórios, mas já estou trabalhando em um exemplo de como fazer isso para ser usado em qualquer situação.

**Comment by diogolovizon** [comment]
Fábio, nos exemplos acima você informa itens relacionados ao Sicredi, o mesmo se aplica ao Sicoob, no qual é o caso?

**Comment by diogolovizon** [comment]
Fábio, tudo bem?

Em contato com o banco entendi o que houve. Acho que vai te ajudar. Veja só:

Sobre o segmento T, foi erro deles. Na verdade é segmento P no qual se referia ao juroMora.
O motivo pelo qual não estava aparecendo juroMora em R$ usando o código 1, é que nas posições onde deveria estar o valor cobrado foi preenchido com zero, ou seja, o bug na verdade está ai!, quando se usa o código 1 o valor não é preenchido. Para que eu possa atende-lo em imediato, usei o código 2 onde coloco o percentual, neste caso funcionou perfeitamente.

Código usado:
`boleto.SetRegEnumValue(CNAB240SegmentoPSicoob.Juros, 1);
  boleto.SetRegEnumValue(CNAB240SegmentoPSicoob.JurosMora, valor);
  boleto.SetRegEnumValue(CNAB240SegmentoPSicoob.JurosData, boleto.DataVencimento.AddDays(1));`

Já sobre o segmento R onde precisa ter a multa, é usado para que quando alguém efetuar um pagamento usando outro banco, ou até mesmo gerar o boleto através do site do sicoob seja atribuído este valor. Portanto, realmente é necessário que tenha este segmento.

Espero ter ajudado, aguardo a próxima atualização. Abraço!

**Comment by impactro** [comment]
Ola,
Publiquei uma nova versão e o exemplo de uso para segmentos opcionais
https://github.com/impactro/Boleto-Test/blob/master/Caixa_SegmentoR.cs

O código SICOOB que estava errado já corrigi também
