### ISSUE TITLE
Nosso número do Sicredi com ano errado

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-ASP.NET#8]
Olá Fábio, descobrimos um Bug na geração de boletos do Sicredi, e só fomos alertados disso agora devido a virada do ano que está próxima. Veja só:

O boleto está gerando o nosso número com base na data de vencimento em questão (2017) mas na verdade deveria ser o ano corrente. exemplo -> http://prntscr.com/de7qrf

Mudança necessária: http://prntscr.com/de7pw7

Para não ter problemas de versões gostaria de saber se vc consegue compartilhar o projeto no git de uma forma em que eu possa contribuir com estas pequenas atualizações sem precisar solicitar a vc.

A não ser que prefira desta forma =)

Você consegue fazer esta atualização, o que sugere? 
Abraços!

**Comment by impactro** [comment]
Ola Diogo, bom dia.

Realmente você está certo, e como você apontou, coloquei minha versão da correção abaixo.
Pode fazer ai do seu lado já mudando a assinatura do método e refletindo isso também na rotina de geração da remessa.

```CS
        /* Sicred_Manual_Beneficiario_Cobranca_CNAB_400.pdf - Página 7
        AA/BXXXXX-D
        AA = Ano atual
        B = Byte (2 a 9). 1 só poderá ser utilizado pela cooperativa.
        XXXXX – Número livre de 00000 a 99999.
        D = Digito Verificador pelo módulo 11.
        */
        public static void MontaNossoNumero(ref string cNossoNumero, ref string cAgenciaNumero, ref string cModalidade, ref string cCodCedente)
        {
            cNossoNumero = CobUtil.Right(cNossoNumero, 5);
            cAgenciaNumero = CobUtil.Right(cAgenciaNumero, 4);
            cModalidade = CobUtil.Right(cModalidade, 2); // Posto da Agência cedente - será colocado em modalidade
            cCodCedente = CobUtil.Right(cCodCedente, 5);

            cNossoNumero = string.Format("{0:yy}2", DateTime.Now) + // 3
                           cNossoNumero;                            // 3+5=8

            // Digito Verificado só do Nosso Numero: aaaappcccccyybnnnnn
            // Aqui o nossonumero já está com o yybnnnnn

            string cDV = CobUtil.Modulo11Especial(
                cAgenciaNumero +
                cModalidade +
                cCodCedente +
                cNossoNumero, 9).ToString();

            cNossoNumero += cDV; // 8+1=9
        }

```

Eu uso um git privado no bitbucket para controle de versão, e a ideia da venda dos fontes é justamente essa, de ninguém ficar na minha dependência e conseguir se virar melhorando ou corrigindo algo que tenha passado despercebido, e eventualmente quem quiser pode colaborar desta forma sugerindo melhorias, e eu vou validando aqui conforme a necessidade.

**Comment by diogolovizon** [comment]
Bom dia Fábio, tudo bem?

Obrigado pela resposta. Nós já efetuamos a mudança conforme você informou.
Muito Obrigado!

Como vai o andamento do CECREDI, se precisar que eu faça o pagamento é só
me enviar o boleto =)
Abraços!

Att,
Diogo Lovizon



Em 7 de dezembro de 2016 08:46, Fabio Ferreira de Souza <
notifications@github.com> escreveu:
